# Generated by Django 2.1.7 on 2019-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_shorturl_shortenurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortenurl',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
