# Generated by Django 2.1.7 on 2019-04-05 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_auto_20190405_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
